# Chassis parameter presets for pure pursuit and unified control.
profiles:
  wide_track:
    track: 0.574                # m (measured track width)
    wheel_base: 0.36            # m
    wheel_speed_max: 3.3        # m/s per wheel (firmware clip 3.5)
    vx_max: 1.5                 # m/s forward cap
    vx_min: -0.4                # m/s reverse cap (disable reverse by setting 0)
    wz_max: 2.5                 # rad/s yaw cap
    accel_limit: 0.8            # m/s^2
    decel_limit: 1.8            # m/s^2
    jerk_limit: 5.0             # m/s^3
    lookahead_base: 0.80        # m
    lookahead_vel_gain: 0.30    # s
    lookahead_time_gain: 0.05   # s^2
    heading_kp: 1.2
    heading_ki: 0.0
    heading_kd: 0.1
    feedforward_gain: 0.9
    goal_tolerance: 0.10        # m
    reverse_enabled: false
    interp_spacing_min: 0.05    # m
    interp_spacing_max: 0.20    # m
    discontinuity_threshold: 0.35 # m
    stageB_controller_mode: 2
    stageC_controller_mode: 2
    curvature_slowdown:
      kappa_threshold: 0.9      # 1/m
      vx_reduction: 0.6         # scale applied when curvature high
